val allWords: Set<String> =
    setOf(
        "Pagamento",
        "Expiram",
        "Expira",
        "Acessos não identificados",
        "Acesso não identificado",
        "Expirará",
        "Conta",
        "Atualize",
        "Detalhes",
        "Gostosa",
        "Sexo",
        "Sexual",
        "Link",
        "Urgência",
        "Emergência",
        "Pressa",
        "Imediatismo",
        "Caráter emergencial",
        "Relevância",
        "Prontidão",
        "Necessidade imediata",
        "Pressing",
        "Urgente",
        "Emergente",
        "Premente",
        "Imprescindível",
        "Crítico",
        "Inadiável",
        "Prioritário",
        "Vital",
        "Instantâneo",
        "Urgentíssimo",
        "Imediato",
        "Instantâneo",
        "Rápido",
        "Precipitado",
        "Repentino",
        "Em tempo real",
        "Já",
        "Sem demora",
        "Ação necessária",
        "Ação imediata",
        "Medida urgente",
        "Necessidade de resposta",
        "Intervenção necessária",
        "Decisão imediata",
        "Ação premente",
        "Providência",
        "Tomada de decisão",
        "Não ignore",
        "Preste atenção",
        "Não desconsidere",
        "Fique atento",
        "Atente-se",
        "Não negligencie",
        "Seja atento",
        "Atente-se a isso",
        "Não ignore este alerta",
        "Última chance",
        "Última oportunidade",
        "Último aviso",
        "Oportunidade final",
        "Última chamada",
        "Oportunidade de ouro",
        "Chance final",
        "Segurança",
        "Proteção",
        "Resguardo",
        "Garantia",
        "Defesa",
        "Tranquilidade",
        "Estabilidade",
        "Resguardo",
        "Salvaguarda",
        "Confidencial",
        "Reservado",
        "Secreto",
        "Privado",
        "Exclusivo",
        "Particular",
        "Sigiloso",
        "Discreto",
        "Verificação",
        "Confirmação",
        "Checagem",
        "Inspeção",
        "Revisão",
        "Auditoria",
        "Análise",
        "Exame",
        "Avaliação",
        "Autenticação",
        "Verificação de identidade",
        "Validação",
        "Confirmação de identidade",
        "Reconhecimento",
        "Certificação",
        "Senha",
        "Código",
        "Palavra-chave",
        "Chave de acesso",
        "PIN",
        "Código de segurança",
        "Código secreto",
        "Segurança da conta",
        "Proteção da conta",
        "Defesa da conta",
        "Segurança digital",
        "Proteção de dados",
        "Segurança online",
        "Proteção de informações",
        "Ofertas",
        "Benefícios",
        "Promoções",
        "Descontos",
        "Vantagens",
        "Oportunidades",
        "Benefícios exclusivos",
        "Ofertas especiais",
        "Promoções imperdíveis",
        "Gratuito",
        "Sem custo",
        "Grátis",
        "Livre",
        "Sem cobrança",
        "Isento de taxas",
        "Promoção",
        "Desconto",
        "Oferta",
        "Barganha",
        "Oportunidade",
        "Vantagem",
        "Liquidação",
        "Você ganhou",
        "Você foi premiado",
        "Parabéns, você venceu",
        "Você foi selecionado",
        "Você conquistou",
        "Você foi o sortudo",
        "Redução de preço",
        "Oferta",
        "Vantagem",
        "Preço especial",
        "Oferta especial",
        "Prêmio",
        "Recompensa",
        "Galardão",
        "Distinção",
        "Conquista",
        "Troféu",
        "Vitória",
        "Comunicação",
        "Contato",
        "Mensagem",
        "Interação",
        "Diálogo",
        "Notificação",
        "Correspondência",
        "Clique aqui",
        "Toque aqui",
        "Pressione aqui",
        "Acesse aqui",
        "Selecione aqui",
        "Clique para continuar",
        "Abra agora",
        "Abra já",
        "Inicie agora",
        "Acesse agora",
        "Comece imediatamente",
        "Clique para abrir",
        "Responda imediatamente",
        "Responda sem demora",
        "Dê uma resposta agora",
        "Responda já",
        "Não demore para responder",
        "Resposta urgente",
        "Contato urgente",
        "Contato imediato",
        "Comunicação urgente",
        "Fale agora",
        "Atende-me rapidamente",
        "Urgente: entre em contato",
        "Atualização necessária",
        "Atualização imediata",
        "Revisão urgente",
        "Necessidade de atualização",
        "Modificação necessária",
        "Atualização importante",
        "Preocupante",
        "Alarmante",
        "Preocupante",
        "Assustador",
        "Desagradável",
        "Inquietante",
        "Alerta",
        "Aviso",
        "Notificação",
        "Sinal de alerta",
        "Alerta urgente",
        "Aviso importante",
        "Cuidado",
        "Ajuda",
        "Assistência",
        "Apoio",
        "Suporte",
        "Socorro",
        "Auxílio",
        "Orientação",
        "Necessidade",
        "Requisito",
        "Exigência",
        "Necessidade urgente",
        "Carência",
        "Demanda",
        "Desejo",
        "Exclusivo",
        "Único",
        "Secreto",
        "Privilegiado",
        "Reservado",
        "Personalizado",
        "Especial",
        "Especial",
        "Único",
        "Excepcional",
        "Diferenciado",
        "Particular",
        "Exclusivo",
        "Singular",
        "Apenas para você",
        "Exclusivo para você",
        "Só para você",
        "Particularmente para você",
        "Personalizado para você",
        "Oportunidade",
        "Chance",
        "Possibilidade",
        "Momento certo",
        "Oportunidade única",
        "Conjuntura favorável",
        "Acesso antecipado",
        "Acesso exclusivo",
        "Acesso precoce",
        "Acesso antecipado",
        "Entrada privilegiada",
        "Exemplos Adicionais",
        "Mais exemplos",
        "Exemplos extras",
        "Exemplos adicionais",
        "Exemplos complementares",
        "Problema",
        "Dificuldade",
        "Desafio",
        "Impedimento",
        "Obstáculo",
        "Questão",
        "Inconveniência",
        "Suporte",
        "Assistência",
        "Ajuda",
        "Apoio",
        "Suporte técnico",
        "Suporte ao cliente",
        "Falha",
        "Erro",
        "Defeito",
        "Quebra",
        "Mal funcionamento",
        "Imperfeição",
        "Falha técnica",
        "Incidente",
        "Evento",
        "Acidente",
        "Acontecimento",
        "Ocorrência",
        "Situação imprevista",
        "Quase lá",
        "Está perto",
        "Próximo",
        "Quase pronto",
        "Em breve",
        "Por pouco",
        "Verifique",
        "Confirme",
        "Cheque",
        "Inspecione",
        "Avalie",
        "Examine",
        "Sua conta",
        "Seu perfil",
        "Sua conta de usuário",
        "Seu cadastro",
        "Sua conta bancária",
        "Informações importantes",
        "Dados essenciais",
        "Detalhes importantes",
        "Informações cruciais",
        "Dados relevantes",
        "Notícia urgente",
        "Prêmio",
        "Gratificação",
        "Benefício",
        "Remuneração",
        "Reconhecimento",
        "Confirmação",
        "Verificação",
        "Validação",
        "Certificação",
        "Aprovação",
        "Banco",
        "Pix",
        "Cheque",
        "Depósito",
        "Dinheiro",
        "Conta bancária",
        "Polícia",
        "Golpe",
        "Senha",
        "Cartão",
        "Governo",
        "Vírus",
        "Prazo final",
        "Expira",
        "Não perca",
        "Expiração iminente",
        "Suspensão",
        "Sua conta será bloqueada",
        "Risco imediato",
        "Contagem regressiva",
        "Impedir acesso",
        "Perigo de perda de dados",
        "Ação rápida necessária",
        "Você foi sorteado",
        "Ganhou um prêmio",
        "Oferta exclusiva",
        "Premiação",
        "Promoção limitada",
        "Ganhe agora",
        "Desconto especial",
        "Bônus gratuito",
        "Oferta irresistível",
        "Receba dinheiro",
        "Oferta especial apenas para você",
        "Verifique sua conta",
        "Confirme de identidade",
        "Verifique seus dados",
        "Atualize sua senha",
        "Preencha seus dados",
        "Solicitação urgente",
        "Recupere sua conta",
        "Seu PIN",
        "Seus dados bancários",
        "Código de verificação",
        "Número de identificação",
        "Sua senha",
        "Confirmação de login",
        "Identificação pessoal",
        "Verificação de identidade automática",
        "Assinatura digital",
        "Sua sessão foi interrompida",
        "Seu acesso foi negado",
        "Verifique a origem",
        "Confirme sua identidade",
        "Código de confirmação",
        "Autenticação falhou",
        "Inicie a verificação",
        "Acesso negado",
        "Problemas no sistema",
        "Ganhe agora",
        "Desconto especial",
        "Bônus gratuito",
        "Oferta irresistível",
        "Receba dinheiro",
        "Oferta especial apenas para você",
        "Solicitação urgente",
        "Recupere sua conta",
        "Seu PIN",
        "Seus dados bancários",
        "Código de verificação",
        "Número de identificação",
        "Sua senha",
        "Confirmação de login",
        "Identificação pessoal",
        "Equipe de segurança",
        "Suporte técnico",
        "Administrador",
        "Departamento de TI",
        "Apoio oficial",
        "Banco",
        "Administração do sistema",
        "Recomendações oficiais",
        "Conta verificada",
        "Certificado de segurança",
        "Verificação de segurança",
        "Helpdesk",
        "Controle de segurança",
        "Suporte ao cliente",
        "Alerta de segurança",
        "Verificação importante",
        "Sua conta foi invadida",
        "Ação imediata necessária",
        "Evite problemas futuros",
        "Proteja seus dados",
        "Seja mais seguro",
        "Proteger sua conta",
        "Evite perdas financeiras",
        "Confirmação urgente",
        "Recupere sua privacidade",
        "Convite especial",
        "Convite especial",
        "Erro de sistema",
        "Falha no pagamento",
        "Problema de segurança",
        "Erro na conta",
        "Falha no login",
        "Ação necessária imediatamente",
        "Falha no banco",
        "Ação incorreta detectada",
        "Erro crítico",
        "Sistemas corrompidos",
        "Problema urgente detectado","Payment",
        "Expire",
        "Expire",
        "Unidentified hits",
        "Unidentified access",
        "Will expire",
        "Account",
        "To update",
        "Details",
        "hot",
        "Sex",
        "Sexual",
        "Link",
        "Urgency",
        "Emergency",
        "Hurry",
        "Immediacy",
        "Emergency nature",
        "Relevance",
        "Readiness",
        "Immediate Need",
        "Pressing",
        "Urgent",
        "Emerging",
        "Pressing",
        "Imdispensable",
        "Critical",
        "Unpostponable",
        "Priority",
        "Vital",
        "Snapshot",
        "Very urgent",
        "Immediate",
        "Snapshot",
        "Fast",
        "Precipitate",
        "Sudden",
        "In real time",
        "Already",
        "Without delay",
        "Action required",
        "Immediate action",
        "Urgent measure",
        "Need for response",
        "Intervention required",
        "Immediate decision",
        "Urgent action",
        "Providence",
        "Decision making",
        "Don't ignore",
        "Pay attention",
        "Do not disregard",
        "Stay tuned",
        "Be careful",
        "Do not neglect",
        "Be careful",
        "Take heed to this",
        "Do not ignore this warning",
        "Last Chance",
        "Last Chance",
        "Last warning",
        "Final Opportunity",
        "Last Call",
        "Golden Opportunity",
        "Final Chance",
        "Security",
        "Protection",
        "Protection",
        "Guarantee",
        "Defense",
        "Tranquility",
        "Stability",
        "Protection",
        "Safeguard",
        "Confidential",
        "Reserved",
        "Secret",
        "Private",
        "Exclusive",
        "Particular",
        "Confidential",
        "Discreet",
        "Verification",
        "Confirmation",
        "Check",
        "Inspection",
        "Revision",
        "Audit",
        "Analysis",
        "Exam",
        "Assessment",
        "Authentication",
        "Identity Verification",
        "Validation",
        "Identity confirmation",
        "Recognition",
        "Certification",
        "Password",
        "Code",
        "Keyword",
        "Access key",
        "PIN",
        "Security code",
        "Secret code",
        "Account security",
        "Account protection",
        "Account defense",
        "Digital security",
        "Data protection",
        "Online security",
        "Information protection",
        "Offers",
        "Benefits",
        "Promotions",
        "Discounts",
        "Advantages",
        "Opportunities",
        "Exclusive benefits",
        "Special offers",
        "Unmissable promotions",
        "Free",
        "No charge",
        "Free",
        "Free",
        "No charge",
        "Fee free",
        "Promotion",
        "Discount",
        "Offer",
        "Bargain",
        "Opportunity",
        "Advantage",
        "Liquidation",
        "You won",
        "You have been awarded",
        "Congratulations, you won",
        "You have been selected",
        "You conquered",
        "You were the lucky one",
        "Price reduction",
        "Offer",
        "Advantage",
        "Special Price",
        "Special offer",
        "Award",
        "Reward",
        "Award",
        "Distinction",
        "Conquest",
        "Trophy",
        "Victory",
        "Communication",
        "Contact",
        "Message",
        "Interaction",
        "Dialogue",
        "Notification",
        "Correspondence",
        "Click here",
        "Touch here",
        "Press here",
        "Access here",
        "Select here",
        "Click to continue",
        "Open now",
        "Open now",
        "Start now",
        "Access now",
        "Start immediately",
        "Click to open",
        "Respond immediately",
        "Respond without delay",
        "Give an answer now",
        "Answer now",
        "Don't delay in responding",
        "Urgent response",
        "Urgent contact",
        "Immediate contact",
        "Urgent communication",
        "Speak Now",
        "Answer me quickly",
        "Urgent: get in touch",
        "Update required",
        "Immediate update",
        "Urgent review",
        "Need update",
        "Modification required",
        "Important update",
        "Worrying",
        "Alarming",
        "Worrying",
        "Scary",
        "Unpleasant",
        "Unsettling",
        "Alert",
        "Notice",
        "Notification",
        "Warning signal",
        "Urgent alert",
        "Important notice",
        "Careful",
        "Help",
        "Assistance",
        "Support",
        "Support",
        "Help",
        "Aid",
        "Guidance",
        "Need",
        "Requirement",
        "Requirement",
        "Urgent need",
        "Lack",
        "Demand",
        "Desire",
        "Exclusive",
        "Single",
        "Secret",
        "Privileged",
        "Reserved",
        "Custom",
        "Special",
        "Special",
        "Single",
        "Exceptional",
        "Differentiated",
        "Particular",
        "Exclusive",
        "Singular",
        "Just for you",
        "Exclusive for you",
        "Just for you",
        "Particularly for you",
        "Customized for you",
        "Opportunity",
        "Chance",
        "Possibility",
        "Right time",
        "Unique opportunity",
        "Favorable situation",
        "Early Access",
        "Exclusive access",
        "Early Access",
        "Early Access",
        "Privileged entrance",
        "Additional Examples",
        "More examples",
        "Extra examples",
        "Additional examples",
        "Complementary examples",
        "Problem",
        "Difficulty",
        "Challenge",
        "Offside",
        "Obstacle",
        "Question",
        "Inconvenience",
        "Support",
        "Assistance",
        "Help",
        "Support",
        "Technical support",
        "Customer Support",
        "Failure",
        "Error",
        "Defect",
        "Break",
        "Malfunction",
        "Imperfection",
        "Technical failure",
        "Incident",
        "Event",
        "Accident",
        "Event",
        "Occurrence",
        "Unforeseen situation",
        "Almost there",
        "It's close",
        "Next",
        "Almost ready",
        "Shortly",
        "Just barely",
        "Check",
        "Confirm",
        "Check",
        "Inspect",
        "Evaluate",
        "Examine",
        "Your account",
        "Your profile",
        "Your user account",
        "Your registration",
        "Your bank account",
        "Important information",
        "Essential data",
        "Important details",
        "Crucial Information",
        "Relevant data",
        "Urgent news",
        "Award",
        "Gratification",
        "Benefit",
        "Remuneration",
        "Recognition",
        "Confirmation",
        "Verification",
        "Validation",
        "Certification",
        "Approval",
        "Bank",
        "Pix",
        "Check",
        "Deposit",
        "Money",
        "Bank account",
        "Police",
        "Scam",
        "Password",
        "Card",
        "Government",
        "Virus",
        "Deadline",
        "Expire",
        "Don't miss it",
        "Expiration imminent",
        "Suspension",
        "Your account will be blocked",
        "Immediate risk",
        "Countdown",
        "Prevent access",
        "Danger of data loss",
        "Quick action required",
        "You were drawn",
        "Won a prize",
        "Exclusive offer",
        "Awards",
        "Limited promotion",
        "Earn now",
        "Special discount",
        "Free Bonus",
        "Irresistible offer",
        "Receive money",
        "Special offer just for you",
        "Check your account",
        "Confirm identity",
        "Check your data",
        "Update your password",
        "Fill in your details",
        "Urgent request",
        "Recover your account",
        "Your PIN",
        "Your bank details",
        "Verification code",
        "Identification number",
        "Your password",
        "Login confirmation",
        "Personal identification",
        "Automatic identity verification",
        "Digital signature",
        "Your session has been interrupted",
        "Your access has been denied",
        "Check source",
        "Confirm your identity",
        "Confirmation code",
        "Authentication failed",
        "Start scan",
        "Access denied",
        "System problems",
        "Earn now",
        "Special discount",
        "Free Bonus",
        "Irresistible offer",
        "Receive money",
        "Special offer just for you",
        "Urgent request",
        "Recover your account",
        "Your PIN",
        "Your bank details",
        "Verification code",
        "Identification number",
        "Your password",
        "Login confirmation",
        "Personal identification",
        "Security team",
        "Technical support",
        "Administrator",
        "IT Department",
        "Official support",
        "Bank",
        "System administration",
        "Official recommendations",
        "Account verified",
        "Security certificate",
        "Security check",
        "Helpdesk",
        "Security control",
        "Customer Support",
        "Security Alert",
        "Important check",
        "Your account has been hacked",
        "Immediate action required",
        "Avoid future problems",
        "Protect your data",
        "Be safer",
        "Protect your account",
        "Avoid financial losses",
        "Urgent confirmation",
        "Recover your privacy",
        "Special Invitation",
        "Special Invitation",
        "System error",
        "Payment failure",
        "Security issue",
        "Account error",
        "Login failed",
        "Action required immediately",
        "Bank failure",
        "Incorrect action detected",
        "Critical error",
        "Corrupt systems",
        "Urgent problem detected",
        "Tax",
        "Taxa",
        "Alfândega",
        "expiring soon",
        "expira",
        "inactivity",
        "inatividade",
        "expire",
        "login",
        "reactive",
        "reative",
        "reativar",
        "update",
        "URL",
        "Plain URL",
        "irregular activity",
        "Atividade suspeita",
        "Atividade irregular",
        "financial",
        "financeiro",
        "suspended",
        "suspensa",
        "password",
        "senha",
        "account",
        "fraudulent transaction",
        "conta",
        "transação fraudulenta",
        "file",
        "shared",
        "arquivo",
        "documento",
        "access",
        "payroll verification",
        "pagamento",
        "verificação",
        "share",
        "profit",
        "suspense",
        "deactivate",
        "desativado",
        "desativada",
        "payment information",
        "informação de pagamento",
        "informações de pagamento",
        "clain",
        "federal",
        "government",
        "governo",

    )
